/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';
import type { ThreeElements } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    icon_spawnPoint: THREE.Mesh;
  };
  materials: {
    icon_spawnpointMat: THREE.MeshStandardMaterial;
  };
};

export function SpawnPoint(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(
    '/spawn-point.glb',
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="icon_spawnPoint"
        castShadow
        receiveShadow
        geometry={nodes.icon_spawnPoint.geometry}
        material={materials.icon_spawnpointMat}
      />
    </group>
  );
}

useGLTF.preload('/spawn-point.glb');
