/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as HubIdRouteImport } from './routes/$hubId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHubsRouteImport } from './routes/api/hubs'
import { Route as HubIdProfileRouteImport } from './routes/$hubId.profile'
import { Route as HubIdEntryRouteImport } from './routes/$hubId.entry'
import { Route as HubIdAudioRouteImport } from './routes/$hubId.audio'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIdRoute = HubIdRouteImport.update({
  id: '/$hubId',
  path: '/$hubId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHubsRoute = ApiHubsRouteImport.update({
  id: '/api/hubs',
  path: '/api/hubs',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIdProfileRoute = HubIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HubIdRoute,
} as any)
const HubIdEntryRoute = HubIdEntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => HubIdRoute,
} as any)
const HubIdAudioRoute = HubIdAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => HubIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$hubId': typeof HubIdRouteWithChildren
  '/signin': typeof SigninRoute
  '/$hubId/audio': typeof HubIdAudioRoute
  '/$hubId/entry': typeof HubIdEntryRoute
  '/$hubId/profile': typeof HubIdProfileRoute
  '/api/hubs': typeof ApiHubsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$hubId': typeof HubIdRouteWithChildren
  '/signin': typeof SigninRoute
  '/$hubId/audio': typeof HubIdAudioRoute
  '/$hubId/entry': typeof HubIdEntryRoute
  '/$hubId/profile': typeof HubIdProfileRoute
  '/api/hubs': typeof ApiHubsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$hubId': typeof HubIdRouteWithChildren
  '/signin': typeof SigninRoute
  '/$hubId/audio': typeof HubIdAudioRoute
  '/$hubId/entry': typeof HubIdEntryRoute
  '/$hubId/profile': typeof HubIdProfileRoute
  '/api/hubs': typeof ApiHubsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$hubId'
    | '/signin'
    | '/$hubId/audio'
    | '/$hubId/entry'
    | '/$hubId/profile'
    | '/api/hubs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$hubId'
    | '/signin'
    | '/$hubId/audio'
    | '/$hubId/entry'
    | '/$hubId/profile'
    | '/api/hubs'
  id:
    | '__root__'
    | '/'
    | '/$hubId'
    | '/signin'
    | '/$hubId/audio'
    | '/$hubId/entry'
    | '/$hubId/profile'
    | '/api/hubs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HubIdRoute: typeof HubIdRouteWithChildren
  SigninRoute: typeof SigninRoute
  ApiHubsRoute: typeof ApiHubsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$hubId': {
      id: '/$hubId'
      path: '/$hubId'
      fullPath: '/$hubId'
      preLoaderRoute: typeof HubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hubs': {
      id: '/api/hubs'
      path: '/api/hubs'
      fullPath: '/api/hubs'
      preLoaderRoute: typeof ApiHubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$hubId/profile': {
      id: '/$hubId/profile'
      path: '/profile'
      fullPath: '/$hubId/profile'
      preLoaderRoute: typeof HubIdProfileRouteImport
      parentRoute: typeof HubIdRoute
    }
    '/$hubId/entry': {
      id: '/$hubId/entry'
      path: '/entry'
      fullPath: '/$hubId/entry'
      preLoaderRoute: typeof HubIdEntryRouteImport
      parentRoute: typeof HubIdRoute
    }
    '/$hubId/audio': {
      id: '/$hubId/audio'
      path: '/audio'
      fullPath: '/$hubId/audio'
      preLoaderRoute: typeof HubIdAudioRouteImport
      parentRoute: typeof HubIdRoute
    }
  }
}

interface HubIdRouteChildren {
  HubIdAudioRoute: typeof HubIdAudioRoute
  HubIdEntryRoute: typeof HubIdEntryRoute
  HubIdProfileRoute: typeof HubIdProfileRoute
}

const HubIdRouteChildren: HubIdRouteChildren = {
  HubIdAudioRoute: HubIdAudioRoute,
  HubIdEntryRoute: HubIdEntryRoute,
  HubIdProfileRoute: HubIdProfileRoute,
}

const HubIdRouteWithChildren = HubIdRoute._addFileChildren(HubIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HubIdRoute: HubIdRouteWithChildren,
  SigninRoute: SigninRoute,
  ApiHubsRoute: ApiHubsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
