/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHubsRouteImport } from './routes/api/hubs'
import { Route as HubIdSlugRouteImport } from './routes/$hubId.$slug'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHubsRoute = ApiHubsRouteImport.update({
  id: '/api/hubs',
  path: '/api/hubs',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIdSlugRoute = HubIdSlugRouteImport.update({
  id: '/$hubId/$slug',
  path: '/$hubId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/$hubId/$slug': typeof HubIdSlugRoute
  '/api/hubs': typeof ApiHubsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/$hubId/$slug': typeof HubIdSlugRoute
  '/api/hubs': typeof ApiHubsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/$hubId/$slug': typeof HubIdSlugRoute
  '/api/hubs': typeof ApiHubsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signin' | '/$hubId/$slug' | '/api/hubs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/$hubId/$slug' | '/api/hubs'
  id: '__root__' | '/' | '/signin' | '/$hubId/$slug' | '/api/hubs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  HubIdSlugRoute: typeof HubIdSlugRoute
  ApiHubsRoute: typeof ApiHubsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hubs': {
      id: '/api/hubs'
      path: '/api/hubs'
      fullPath: '/api/hubs'
      preLoaderRoute: typeof ApiHubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$hubId/$slug': {
      id: '/$hubId/$slug'
      path: '/$hubId/$slug'
      fullPath: '/$hubId/$slug'
      preLoaderRoute: typeof HubIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  HubIdSlugRoute: HubIdSlugRoute,
  ApiHubsRoute: ApiHubsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
